import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import Navbar from "./(components)/Navbar";
import { Toaster } from "@/components/ui/sonner";

import ProviderAuth from "@/providers/SessionProvider";
import { TooltipProvider } from "@/components/ui/tooltip";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  


  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={` h-full antialiased font-manrope`}

    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
        <ProviderAuth>

          {children}
          <Toaster />
        </ProviderAuth>
        </TooltipProvider>
      </body>
    </html>
  );
}
